import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Face from '../compoents/Face';
import { getStaticPosts } from '../lib/posts';
//import { Post } from '../lib/post';
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'





const Home: NextPage = ({allpostsdata}: any) => {

  
  
 // getStaticPosts();
  return (
    <div className={styles.container}>
      <Head>
        <title>Bdbmzwsc's site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
        <Face />
        <div className={styles.grid}>
          {allpostsdata.map(({id,title,date,des}: any)=>{
            return(
              <a className={styles.card} href={`/post/${id}`}>
                  <h2>{title}</h2>
                  <p>{des}</p>
              </a>
            )
          })}
          </div>
        
      </main>
    </div>
  )
}




export default Home

export const getStaticProps: GetStaticProps= async () =>{
  const allpostsdata= getStaticPosts();
  return {
     props: {
      allpostsdata
     }
  }
}

