import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Face from '../compoents/Face';
import { getStaticPosts } from '../lib/posts';
import Postcard from '../compoents/Postcard';
//import { Post } from '../lib/post';
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'





const Home: NextPage = ({allpostsdata}: any) => {

             {/*   <a className={styles.btna} href={`/post/${id}`}>
               
               <span><h2>{title}</h2></span>
                  <p>{des}</p>
                  <div className={styles.date}>date: {date}</div>
                  
              </a>*/} 
  
 // getStaticPosts();
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Bdbmzwsc's site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
        <Face />
        <div className={styles.grid}>
          {allpostsdata.map(({id,title,date,des,backimg}: any)=>{
            return(
              <Postcard id={id} title={title} date={date} des={des} backimg={backimg}/>

            )
          })}
          </div>
        
      </main>
    </div>
  )
}




export default Home

export const getStaticProps: GetStaticProps= async () =>{
  const allpostsdata= getStaticPosts();
  return {
     props: {
      allpostsdata
     }
  }
}

